dist: trusty

jobs:
  include:
    - stage: run tests
      language: go
      go:
        - 1.16.x
      before_install:
        - go get github.com/mattn/goveralls
      script:
        - $GOPATH/bin/goveralls -service=travis-ci
    - stage: build docker image
      if: type != pull_request AND branch = master
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t redis-inventory .
        - docker images
        - docker tag redis-inventory $DOCKER_USERNAME/redis-inventory
        - docker push $DOCKER_USERNAME/redis-inventory
    - stage: test docker image
      if: type != pull_request AND branch = master
      script: docker run --rm $DOCKER_USERNAME/redis-inventory help
